# Run tests in Docker `docker-compose up` on Node.js v18
# - install node deps first `docker-compose run agenda npm install`
version: "3"
services:
  agenda:
    image: node:18
    command: npm test
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_HOST=mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
